POST http://localhost:3001/api/persons
content-type: application/json 

{
    "name": "Jerry Seinfeld",
    "number": "310 545 8827"
}

###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/61858f074ab653c39c60d335