GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
content-type: application/json 

{
    "name": "Jerry Seinfeld",
    "number": "310 545 8827"
}

###
DELETE http://localhost:3001/api/persons/2707